# Generated by Django 3.1.6 on 2021-02-25 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=255)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.level')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=255)),
                ('license_plate', models.CharField(max_length=255)),
                ('arrived_at', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_at', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_paid', models.IntegerField(blank=True, null=True)),
                ('spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vehicles.spot')),
            ],
        ),
    ]
