# Generated by Django 3.1.6 on 2021-02-23 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='available_spots',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='levels.spot'),
        ),
        migrations.AlterField(
            model_name='level',
            name='fill_priority',
            field=models.IntegerField(blank=True),
        ),
    ]
