# Generated by Django 3.1.6 on 2021-02-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_auto_20210223_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='fill_priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
